### ISSUE TITLE
Add a function definition administrator

### ISSUE THREAD

**Issue by Gautaum** [Gautaum/c-#1]
Inside function administrator definition call four function that are 1.) add 2.) modify 3.) delete 4.)exit

**Comment by Prem-Mittal** [comment]
Please assign this issue to me. I have gone through entire code and I can solve this issue.

**Comment by Gautaum** [comment]
Ok I assign this issue to you! @Prem-Mittal

**Comment by Gautaum** [comment]
The issue has been solved
